# Generated by Django 5.1.3 on 2024-11-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alarm_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
